# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  #  global_miles_airline_api client class.
  class GlobalMilesAirlineApiClient
    # Singleton access to members controller.
    # @return [MembersController] Returns the controller instance.
    def members
      MembersController.instance
    end

    # Singleton access to flights controller.
    # @return [FlightsController] Returns the controller instance.
    def flights
      FlightsController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end
  end
end
