# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # A complex object for definition of the award mile calculation logic.
  class AwardMilesRules < BaseModel
    # The type of the award base. The possible values are 'distance_based' and
    # 'fair_based'.
    # @return [AwardTypeEnum]
    attr_accessor :award_type

    # The ratio for calculating base mile from distance or fair. Possible value
    # is an integer between 1 and 100.
    # @return [Integer]
    attr_accessor :base_ratio

    # The additional mile ratio for a check-in operation. Possible value as an
    # integer between 0 and 100.
    # @return [Integer]
    attr_accessor :checkin_ratio

    # The additional mile ratio for a check-out operation. Possible value as an
    # integer between 0 and 100.
    # @return [Integer]
    attr_accessor :checkout_ratio

    # The additional mile ratio for a survey. Possible value as an integer
    # between 0 and 100.
    # @return [Integer]
    attr_accessor :survey_ratio

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['award_type'] = 'award_type'
      @_hash['base_ratio'] = 'base_ratio'
      @_hash['checkin_ratio'] = 'checkin_ratio'
      @_hash['checkout_ratio'] = 'checkout_ratio'
      @_hash['survey_ratio'] = 'survey_ratio'
      @_hash
    end

    def initialize(award_type = nil,
                   base_ratio = nil,
                   checkin_ratio = nil,
                   checkout_ratio = nil,
                   survey_ratio = nil)
      @award_type = award_type
      @base_ratio = base_ratio
      @checkin_ratio = checkin_ratio
      @checkout_ratio = checkout_ratio
      @survey_ratio = survey_ratio
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      award_type = hash['award_type']
      base_ratio = hash['base_ratio']
      checkin_ratio = hash['checkin_ratio']
      checkout_ratio = hash['checkout_ratio']
      survey_ratio = hash['survey_ratio']

      # Create object from extracted values.
      AwardMilesRules.new(award_type,
                          base_ratio,
                          checkin_ratio,
                          checkout_ratio,
                          survey_ratio)
    end
  end
end
