# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # The type of the award base. The possible values are 'distance_based' and
  # 'fare_based'.
  class AwardTypeEnum
    AWARD_TYPE_ENUM = [
      # TODO: Write general description for DISTANCE_BASED
      DISTANCE_BASED = 'distance_based'.freeze,

      # TODO: Write general description for FARE_BASED
      FARE_BASED = 'fare_based'.freeze
    ].freeze
  end
end
