# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # Cabin type of the flight.
  class CabinTypeEnum
    CABIN_TYPE_ENUM = [
      # First Class Discounted
      A = 'A'.freeze,

      # Economy/Coach
      B = 'B'.freeze,

      # Business Class
      C = 'C'.freeze,

      # Business Class Discounted
      D = 'D'.freeze,

      # Shuttle Service (no reservation allowed) or Economy/Coach Discounted
      E = 'E'.freeze,

      # First Class
      F = 'F'.freeze,

      # Conditional Reservation
      G = 'G'.freeze,

      # Economy/Coach Discounted
      H = 'H'.freeze,

      # Business Class Premium
      J = 'J'.freeze,

      # Economy/Coach Discounted
      K = 'K'.freeze,

      # Economy/Coach Discounted
      L = 'L'.freeze,

      # Economy/Coach Discounted
      M = 'M'.freeze,

      # Economy/Coach Discounted
      N = 'N'.freeze,

      # First Class Premium
      P = 'P'.freeze,

      # Economy/Coach Discounted
      Q = 'Q'.freeze,

      # First Class Suite or Supersonic (discontinued)
      R = 'R'.freeze,

      # Economy/Coach
      S = 'S'.freeze,

      # Economy/Coach Discounted
      T = 'T'.freeze,

      # Shuttle Service
      U = 'U'.freeze,

      # Economy/Coach Discounted
      V = 'V'.freeze,

      # Economy/Coach Premium
      W = 'W'.freeze,

      # Economy/Coach Discounted
      X = 'X'.freeze,

      # Economy/Coach
      Y = 'Y'.freeze,

      # Business Class Discounted
      Z = 'Z'.freeze
    ].freeze
  end
end
