# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # Cabin type of the flight.
  class CabinTypeEnum
    CABIN_TYPE_ENUM = [
      # Unknown
      UNKNOWN = 'unknown'.freeze,

      # Discount Economy
      DISCOUNT_ECONOMY = 'discount_economy'.freeze,

      # Economy
      ECONOMY = 'economy'.freeze,

      # Full Economy
      FULL_ECONOMY = 'full_economy'.freeze,

      # Premium Economy
      PREMIUM_ECONOMY = 'premium_economy'.freeze,

      # Discount Business
      DISCOUNT_BUSINESS = 'discount_business'.freeze,

      # Business
      BUSINESS = 'business'.freeze,

      # Premium Business
      PREMIUM_BUSINESS = 'premium_business'.freeze,

      # First
      FIRST = 'first'.freeze,

      # Premium First
      PREMIUM_FIRST = 'premium_first'.freeze
    ].freeze
  end
end
