# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # Type of card
  class CardTypeEnum
    CARD_TYPE_ENUM = [
      # Unknown
      UNKNOWN = 'unknown'.freeze,

      # Basic
      BASIC = 'basic'.freeze,

      # Red
      RED = 'red'.freeze,

      # Silver
      SILVER = 'silver'.freeze,

      # Gold
      GOLD = 'gold'.freeze,

      # Platinum
      PLATINUM = 'platinum'.freeze,

      # Diamond
      DIAMOND = 'diamond'.freeze,

      # Corparate
      CORPARATE = 'corparate'.freeze
    ].freeze
  end
end
