# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # ExtraInfoType.
  class ExtraInfoTypeEnum
    EXTRA_INFO_TYPE_ENUM = [
      # Nationality
      NATIONALITY = 'nationality'.freeze,

      # National ID Number
      NATIONAL_ID_NUMBER = 'national_id_number'.freeze,

      # Language
      LANGUAGE = 'language'.freeze,

      # Gender
      GENDER = 'gender'.freeze,

      # Birthday
      BIRTHDAY = 'birthday'.freeze,

      # Academic Title
      ACADEMIC_TITLE = 'academic_title'.freeze,

      # Address
      ADDRESS = 'address'.freeze,

      # Country
      COUNTRY = 'country'.freeze,

      # City
      CITY = 'city'.freeze,

      # Area
      AREA = 'area'.freeze,

      # Zip Code
      ZIP_CODE = 'zip_code'.freeze,

      # Password
      PASSWORD = 'password'.freeze
    ].freeze
  end
end
