# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'response'

module GlobalMilesAirlineApi
  # FlightStatusResponse Model.
  class FlightStatusResponse < Response
    # The final status of flight. The possible values are 'used', 'unused' and
    # 'reissued'. For the reissued tickets the following new flight information
    # must provided.
    # @return [FlightStatusTypeEnum]
    attr_accessor :flight_status

    # A complex for the flight. It is only accepted for reissued status.
    # @return [FlightMax]
    attr_accessor :flight

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['flight_status'] = 'flight_status'
      @_hash['flight'] = 'flight'
      @_hash = super().merge(@_hash)
      @_hash
    end

    def initialize(flight_status = nil,
                   flight = nil,
                   status = nil,
                   message = nil)
      @flight_status = flight_status
      @flight = flight

      # Call the constructor of the base class
      super(status,
            message)
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      flight_status = hash['flight_status']
      flight = FlightMax.from_hash(hash['flight']) if hash['flight']
      status = hash['status']
      message = hash['message']

      # Create object from extracted values.
      FlightStatusResponse.new(flight_status,
                               flight,
                               status,
                               message)
    end
  end
end
