# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # The final status of flight. The possible values are 'used', 'unused' and
  # 'reissued'.
  class FlightStatusTypeEnum
    FLIGHT_STATUS_TYPE_ENUM = [
      # Used
      USED = 'used'.freeze,

      # Unused
      UNUSED = 'unused'.freeze,

      # Reissued
      REISSUED = 'reissued'.freeze
    ].freeze
  end
end
