# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # FlightCreateRequest Model.
  class FlightCreateRequest < BaseModel
    # A complex object for definition of the award mile calculation logic.
    # @return [AwardMilesRules]
    attr_accessor :award_miles_rules

    # A complex object for representing a passenger.
    # @return [PassengerMax]
    attr_accessor :passenger

    # Routing type of the flights.
    # @return [RoutingTypeEnum]
    attr_accessor :routing_type

    # An array of flights. We are expecting one flight for one way trip and two
    # flights for round trip.
    # @return [List of FlightMax]
    attr_accessor :flights

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['award_miles_rules'] = 'award_miles_rules'
      @_hash['passenger'] = 'passenger'
      @_hash['routing_type'] = 'routing_type'
      @_hash['flights'] = 'flights'
      @_hash
    end

    def initialize(award_miles_rules = nil,
                   passenger = nil,
                   routing_type = nil,
                   flights = nil)
      @award_miles_rules = award_miles_rules
      @passenger = passenger
      @routing_type = routing_type
      @flights = flights
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      award_miles_rules = AwardMilesRules.from_hash(hash['award_miles_rules']) if
        hash['award_miles_rules']
      passenger = PassengerMax.from_hash(hash['passenger']) if
        hash['passenger']
      routing_type = hash['routing_type']
      # Parameter is an array, so we need to iterate through it
      flights = nil
      unless hash['flights'].nil?
        flights = []
        hash['flights'].each do |structure|
          flights << (FlightMax.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      FlightCreateRequest.new(award_miles_rules,
                              passenger,
                              routing_type,
                              flights)
    end
  end
end
