# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # FlightMin Model.
  class FlightMin < BaseModel
    # Passenger name record of the flight.
    # @return [String]
    attr_accessor :pnr

    # Ticket number of the passenger.
    # @return [String]
    attr_accessor :ticket_number

    # Number of the flight.
    # @return [String]
    attr_accessor :flight_number

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pnr'] = 'pnr'
      @_hash['ticket_number'] = 'ticket_number'
      @_hash['flight_number'] = 'flight_number'
      @_hash
    end

    def initialize(pnr = nil,
                   ticket_number = nil,
                   flight_number = nil)
      @pnr = pnr
      @ticket_number = ticket_number
      @flight_number = flight_number
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pnr = hash['pnr']
      ticket_number = hash['ticket_number']
      flight_number = hash['flight_number']

      # Create object from extracted values.
      FlightMin.new(pnr,
                    ticket_number,
                    flight_number)
    end
  end
end
