# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # GenderType.
  class GenderTypeEnum
    GENDER_TYPE_ENUM = [
      # Male
      MALE = 'male'.freeze,

      # Female
      FEMALE = 'female'.freeze,

      # Unknown
      UNKNOWN = 'unknown'.freeze
    ].freeze
  end
end
