# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # LanguageType.
  class LanguageTypeEnum
    LANGUAGE_TYPE_ENUM = [
      # for English
      EN = 'en'.freeze,

      # for Turkish
      TR = 'tr'.freeze
    ].freeze
  end
end
