# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # MemberSearchRequest Model.
  class MemberSearchRequest < BaseModel
    # FFP number of member
    # @return [String]
    attr_accessor :ffp_number

    # First name
    # @return [String]
    attr_accessor :first_name

    # Last name
    # @return [String]
    attr_accessor :last_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ffp_number'] = 'ffp_number'
      @_hash['first_name'] = 'first_name'
      @_hash['last_name'] = 'last_name'
      @_hash
    end

    def initialize(ffp_number = nil,
                   first_name = nil,
                   last_name = nil)
      @ffp_number = ffp_number
      @first_name = first_name
      @last_name = last_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ffp_number = hash['ffp_number']
      first_name = hash['first_name']
      last_name = hash['last_name']

      # Create object from extracted values.
      MemberSearchRequest.new(ffp_number,
                              first_name,
                              last_name)
    end
  end
end
