# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'response'

module GlobalMilesAirlineApi
  # NewMemberResponse Model.
  class NewMemberResponse < Response
    # Card number of frequent flyer.
    # @return [String]
    attr_accessor :ffp_number

    # Type of the miles card.
    # @return [CardTypeEnum]
    attr_accessor :card_type

    # If the provided information is not enough to create a ffp member, this
    # field can use to get new information. The possible values are language,
    # gender, birthday, nationality, national_id_number, academic_title,
    # address, country, city, area, zip_code, password. We will collect the
    # additional information from user and will enhance the first request and
    # will send it again.
    # @return [List of ExtraInfoTypeEnum]
    attr_accessor :need_extra_info

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ffp_number'] = 'ffp_number'
      @_hash['card_type'] = 'card_type'
      @_hash['need_extra_info'] = 'need_extra_info'
      @_hash = super().merge(@_hash)
      @_hash
    end

    def initialize(status = nil,
                   ffp_number = nil,
                   card_type = nil,
                   need_extra_info = nil,
                   message = nil)
      @ffp_number = ffp_number
      @card_type = card_type
      @need_extra_info = need_extra_info

      # Call the constructor of the base class
      super(status,
            message)
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash['status']
      ffp_number = hash['ffp_number']
      card_type = hash['card_type']
      need_extra_info = hash['need_extra_info']
      message = hash['message']

      # Create object from extracted values.
      NewMemberResponse.new(status,
                            ffp_number,
                            card_type,
                            need_extra_info,
                            message)
    end
  end
end
