# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # A complex object for representing a minimal passenger information.
  class PassengerMin < BaseModel
    # First name of the passenger. Maximum length is 40 characters.
    # @return [String]
    attr_accessor :first_name

    # Last name of the passenger. Maximum length is 40 characters.
    # @return [String]
    attr_accessor :last_name

    # Mobile phone number of the passenger. It is a unique identifier for
    # passengers in the system. The format is E.164.
    # @return [String]
    attr_accessor :mobile

    # Email address of the passenger.
    # @return [String]
    attr_accessor :email

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first_name'] = 'first_name'
      @_hash['last_name'] = 'last_name'
      @_hash['mobile'] = 'mobile'
      @_hash['email'] = 'email'
      @_hash
    end

    def initialize(first_name = nil,
                   last_name = nil,
                   mobile = nil,
                   email = nil)
      @first_name = first_name
      @last_name = last_name
      @mobile = mobile
      @email = email
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      first_name = hash['first_name']
      last_name = hash['last_name']
      mobile = hash['mobile']
      email = hash['email']

      # Create object from extracted values.
      PassengerMin.new(first_name,
                       last_name,
                       mobile,
                       email)
    end
  end
end
