# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # Routing type of the flights. 'one_way' for one way, 'round_trip' for round
  # trip.
  class RoutingTypeEnum
    ROUTING_TYPE_ENUM = [
      # One way trip indicator.
      ONE_WAY = 'one_way'.freeze,

      # Round trip indicator.
      ROUND_TRIP = 'round_trip'.freeze
    ].freeze
  end
end
