# global_miles_airline_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesAirlineApi
  # Type of tiers
  class TierTypeEnum
    TIER_TYPE_ENUM = [
      # Unknown
      UNKNOWN = 'unknown'.freeze,

      # Basic
      BASIC = 'basic'.freeze,

      # Red
      TIER1 = 'tier1'.freeze,

      # Silver
      TIER2 = 'tier2'.freeze,

      # Gold
      TIER3 = 'tier3'.freeze,

      # Platinum
      TIER4 = 'tier4'.freeze,

      # Diamond
      TIER5 = 'tier5'.freeze,

      # Corparate
      TIER6 = 'tier6'.freeze
    ].freeze
  end
end
