# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).
require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'global_miles_airline_api/api_helper.rb'
require_relative 'global_miles_airline_api/global_miles_airline_api_client.rb'

# Http
require_relative 'global_miles_airline_api/http/http_call_back.rb'
require_relative 'global_miles_airline_api/http/http_client.rb'
require_relative 'global_miles_airline_api/http/http_method_enum.rb'
require_relative 'global_miles_airline_api/http/http_request.rb'
require_relative 'global_miles_airline_api/http/http_response.rb'
require_relative 'global_miles_airline_api/http/http_context.rb'
require_relative 'global_miles_airline_api/http/faraday_client.rb'

# Models
require_relative 'global_miles_airline_api/models/base_model.rb'
require_relative 'global_miles_airline_api/models/flight_create_request.rb'
require_relative 'global_miles_airline_api/models/response.rb'
require_relative 'global_miles_airline_api/models/amount.rb'
require_relative 'global_miles_airline_api/models/flight_max.rb'
require_relative 'global_miles_airline_api/models/passenger_max.rb'
require_relative 'global_miles_airline_api/models/award_miles_rules.rb'
require_relative 'global_miles_airline_api/models/member_search_request.rb'
require_relative 'global_miles_airline_api/models/passenger_min.rb'
require_relative 'global_miles_airline_api/models/new_member_request.rb'
require_relative 'global_miles_airline_api/models/flight_min.rb'
require_relative 'global_miles_airline_api/models/member_search_response.rb'
require_relative 'global_miles_airline_api/models/flight_simple.rb'
require_relative 'global_miles_airline_api/models/user.rb'
require_relative 'global_miles_airline_api/models/flight_status_response.rb'
require_relative 'global_miles_airline_api/models/flight_status_request.rb'
require_relative 'global_miles_airline_api/models/new_member_response.rb'
require_relative 'global_miles_airline_api/models/gender_type_enum.rb'
require_relative 'global_miles_airline_api/models/language_type_enum.rb'
require_relative 'global_miles_airline_api/models/award_type_enum.rb'
require_relative 'global_miles_airline_api/models/flight_status_type_enum.rb'
require_relative 'global_miles_airline_api/models/extra_info_type_enum.rb'
require_relative 'global_miles_airline_api/models/routing_type_enum.rb'
require_relative 'global_miles_airline_api/models/cabin_type_enum.rb'
require_relative 'global_miles_airline_api/models/card_type_enum.rb'

# Exceptions
require_relative 'global_miles_airline_api/exceptions/api_exception.rb'

require_relative 'global_miles_airline_api/configuration.rb'

# Controllers
require_relative 'global_miles_airline_api/controllers/base_controller.rb'
require_relative 'global_miles_airline_api/controllers/flights_controller.rb'
